### ISSUE TITLE
Add API to detect available controllers and functionalities

### ISSUE THREAD

**Issue by nixpanic** [csi-addons/spec#12]
Similar to the CSI Controllers, I imagine it would benefit consumers to have a detection mechanism of what Controllers are available, and what functionalities it provides.

An [**Identity Service**](https://github.com/container-storage-interface/spec/blob/master/spec.md#identity-service-rpc) kind of API could provide access to details like:

- ReplicationController
  - API version, other information about provider
  - capabilities: `ENABLE_DISABLE`, `PROMOTE_DEMOTE`, `RESYNC`
- FencingController
  - API version, other information about provider
  - capabilities: `BLOCK_NODE`, `UNBLOCK_NODE`, `NODE_RECOVERY`
- DataEncryptionController
  - API version, other information about provider
  - capabilities: `KEY_ROTATION`, `SHRED`

Adding the Identify Service from the beginning shows the intent to do more than replication alone. The README mentions fencing in a diagram, but it is omitted everywhere else.

**Comment by Madhu-1** [comment]
@nixpanic Thanks for the suggestion its good to expose this one will work on this one.

**Comment by nixpanic** [comment]
Work-in-progress ideas and design is now posted at https://hackmd.io/BILt9i8tS8SzyDKsaCc9WA?view .

**Comment by humblec** [comment]
Thanks @nixpanic , will try to take it forward!

**Comment by nixpanic** [comment]
Should have been closed through #28
