### ISSUE TITLE
Add update time to the ResyncVolumeResponse

### ISSUE THREAD

**Issue by Madhu-1** [csi-addons/spec#24]
add update_time/last_sync_time to the ResyncVolumeResponse to update the actual resync that happened to time in the backend and this field is optional. 

```proto
// ResyncVolumeResponse holds the information to send when
// volume is successfully resynced.
message ResyncVolumeResponse{
  // Indicates that the volume is ready to use.
  // The default value is false.
  // This field is REQUIRED.
  bool ready = 1;
   // Timestamp of last resync update on the volume
  // This field is optional.
  .google.protobuf.Timestamp updated_time = 4;
}
```

open for suggestion on the field name `updated_time` or `last_resync_update` anything else?

CC @ShyamsundarR @raghavendra-talur @oriyarde

**Comment by nixpanic** [comment]
Use `GetVolumeReplicationInfo` as defined in #44 for this.
