### ISSUE TITLE
add a CI to make sure user pushed pb files after changed spec section in readme files.

### ISSUE THREAD

**Issue by Madhu-1** [csi-addons/spec#34]
Currently, we don't have any check-in CI to make sure the user-generated the profiles after changing some text in the proto spec in Readme.

example PR this happened is https://github.com/csi-addons/spec/pull/33. good to check this in CI.

**Comment by humblec** [comment]
@Madhu-1 you mean user generated `proto files` , Isnt it ?

**Comment by Madhu-1** [comment]
@nixpanic looks like its not solved due to the non-zero exit problem with Makefiles https://github.community/t/makefile-non-zero-exit-code-still-marked-as-succeeded/122638. reopening it for now

**Comment by Madhu-1** [comment]
CI passed on https://github.com/csi-addons/spec/pull/33 even though we don't have lib changes

**Comment by nixpanic** [comment]
> CI passed on #33 even though we don't have lib changes

Yes, the `make check-changes` reports the missing updated generated files. But instead of returning a non-zero status, the `exit 1` is part of the `echo "files got changes" exit 1` output string.
